module ExamResults {
	requires transitive javafx.graphics;
	exports ExamResults;
	requires java.sql;
	requires java.sql.rowset;
	requires java.datatransfer;
	requires javafx.controls;
	requires javafx.base;
	requires javafx.fxml;
	requires javafx.media;
	requires javafx.web;
	requires javafx.swing;
	requires junit;
	requires org.junit.jupiter.api;
	requires org.junit.jupiter.engine;
	requires org.assertj.core;
	requires org.junit.platform.commons;
	requires org.junit.jupiter.migrationsupport;
	requires org.junit.jupiter.params;
	requires org.junit.platform.engine;
	requires org.junit.platform.launcher;
	requires org.junit.platform.runner;
	requires org.junit.platform.suite.api;
	requires org.junit.platform.suite.commons;
	requires org.junit.platform.suite.engine;
	requires org.junit.vintage.engine;
	requires java.base;
	requires java.compiler;
	requires org.hamcrest.core.deprecated;
}